Added client sampleid to worksheet printview
senaite/senaite.core pull request #1627
Opened 2020-09-30 08:52 UTC by lawrence02

## Description of the issue/feature this PR addresses

Linked issue: https://github.com/senaite/senaite.core/issues/1612

## Current behavior before PR

Worksheet templates print does not show "client sample id"

## Desired behavior after PR is merged

Worksheet templates print view should include "client sample id" option

--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

2020-10-01 19:55 UTC, lawrence02 commented
@xispa Could you kindly review.

2020-10-01 20:30 UTC, xispa requested changes
Thank you @lawrence02 , please add an entry to https://github.com/senaite/senaite.core/blob/1.3.x/CHANGES.rst so we can accept and merge this one!

2020-10-02 11:07 UTC, xispa approved these changes

2020-10-02 11:09 UTC, xispa approved these changes

2020-10-02 11:09 UTC, merged