Fix for Report section displays date pickers in Chinese
senaite/senaite.core pull request #1634
Opened 2020-10-06 08:50 UTC by Espurna

## Description of the issue/feature this PR addresses

Linked issue: https://github.com/senaite/senaite.core/issues/1633

## Current behavior before PR

Issue explained here: https://github.com/senaite/senaite.core/pull/1570/

## Desired behavior after PR is merged

"Date picker 2 months" in reports uses the proper language.

--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

2020-10-07 09:03 UTC, xispa requested changes
It does work to me..... in which report you see this problem?

2020-10-07 09:03 UTC, xispa commented on CHANGES.rst
> +- #1633 Fix report section displays date pickers in Chinese
@Espurna always add the changelog entry to the top of the list. They are always sorted from newest to oldest, as versions.

2020-10-07 09:28 UTC, Espurna commented
> It does work to me..... in which report you see this problem?

To all the reports.

2020-10-07 12:37 UTC, xispa commented
@Espurna I've done some cleanup. Can you confirm date pickers are working properly in your instance?

2020-10-07 18:19 UTC, Espurna commented
@xispa After you changes, it is still working well.

2020-10-08 19:35 UTC, xispa approved these changes

2020-10-08 19:36 UTC, xispa approved these changes

2020-10-08 19:36 UTC, merged