Wttemplate method select
senaite/senaite.core pull request #1887
Opened 2021-11-26 09:02 UTC by Lunga001

## Description of the issue/feature this PR addresses

Linked issue: https://github.com/senaite/senaite.core/issues/

## Current behavior before PR

## Desired behavior after PR is merged

--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

2022-04-26 12:17 UTC, ramonski commented
Hi @Lunga001, what is the state of this PR?

2022-04-29 04:11 UTC, Lunga001 commented
Updated @ramonski the PR is ready. Sorry about the delay, just that I wasn't sure removing selection widget was the best way to go about it.

2022-04-29 08:32 UTC, xispa requested changes
Thanks @Lunga001, but it does not work, see comments. 

Note this `AJAXGetWorksheetTemplateInstruments` class and the javascript are old-school. You might consider to use the "EditForm" introduced with https://github.com/senaite/senaite.core/pull/1719 to achieve this instrument-filtering functionality in a more elegant way, and with extrapoints for the removal of old code.

2022-04-29 08:32 UTC, xispa commented on src/bika/lims/content/worksheettemplate.py
>      ),
Removing this widget makes the filtering of instruments when a method is selected to not work at all. The reason is that the javascript in charge of updating the list of methods expects the control to be a `SelectionWidget` here: https://github.com/senaite/senaite.core/blob/2.x/src/senaite/core/browser/static/js/bika.lims.worksheettemplate.js#L11

2022-04-29 08:32 UTC, xispa commented on src/bika/lims/browser/worksheettemplate.py
> +        except api.APIError:
Better remove this try/except. System might fail silently otherwise.

2022-04-29 17:07 UTC, Lunga001 commented
> Thanks @Lunga001, but it does not work, see comments.
> 
> Note this `AJAXGetWorksheetTemplateInstruments` class and the javascript are old-school. You might consider to use the "EditForm" introduced with #1719 to achieve this instrument-filtering functionality in a more elegant way, and with extrapoints for the removal of old code.

Gave EditForm a shot

2022-05-03 15:01 UTC, xispa requested changes
@Lunga001 please pull, note I've pushed a commit for cleanup here https://github.com/senaite/senaite.core/pull/1887/commits/3312335b1fd072b02fc375e8cadc16a33ec55125

I also left some comments

2022-05-03 15:01 UTC, xispa commented on src/senaite/core/browser/form/adapters/configure.zcml
> +
Please remove this instead if commenting if is not used

2022-05-03 15:01 UTC, xispa commented on src/senaite/core/browser/form/adapters/worksheettemplate.py
> +            method = api.get_object_by_uid(value[0])
Note that `value[0]` can be empty. You get `APIError: get_object_by_uid requires UID as first argument; got  instead` in such case. Remember you can check if something is an UID with `api.is_uid(someting)`

2022-05-03 15:01 UTC, xispa commented on src/senaite/core/browser/form/adapters/worksheettemplate.py
> +            instruments = self.get_available_instruments_for(method)
You can omit this `get_available_instruments_for` and rely on method's `getInstruments` directly here, cause in accordance with my previous comment, at this point you should have a valid method already

2022-05-03 15:01 UTC, xispa commented on src/senaite/core/browser/form/adapters/worksheettemplate.py
> +                    "options": i_opts})
this should be empty instead of `i_opts`, right?

2022-05-04 08:21 UTC, xispa approved these changes

2022-05-04 08:22 UTC, merged