Allow to edit analysis conditions
senaite/senaite.core pull request #1935
Opened 2022-02-14 12:02 UTC by xispa

## Description of the issue/feature this PR addresses

This Pull Request adds the possibility to edit the (pre) conditions of existing analyses. Analysis (pre) conditions were introduced in https://github.com/senaite/senaite.core/pull/1854

An icon below the "info" icon in analyses listing is displayed when the analysis has (pre)conditions set. When clicked, an overlay form is displayed for the update of those conditions.

## Current behavior before PR

User cannot edit (pre) conditions of non-yet verified analyses

## Desired behavior after PR is merged

User can edit (pre) conditions of non-yet verified analyses

![Captura de 2022-02-14 12-58-07](https://user-images.githubusercontent.com/832627/153860668-66b36dc7-0fd5-4596-90ea-4a2abb19894b.png)

--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

2022-02-14 22:09 UTC, ramonski requested changes
Only minor changes needed before we can merge it.
It is a pity that the modal overlay is bound to workflow actions only:
https://github.com/senaite/senaite.app.listing/blob/2.x/webpack/app/listing.coffee#L773

2022-02-14 22:09 UTC, ramonski commented on src/senaite/core/browser/modals/templates/set_analysis_conditions.pt
> +            <table class="table table-condensed small">
Please use `table-sm` instead of `table-condensed`
https://getbootstrap.com/docs/4.6/migration/#tables

2022-02-14 22:09 UTC, ramonski commented on src/senaite/core/browser/modals/analysis.py
> +            return uid
for which case is the UID not inside `form`?
Maybe better if this is really needed:
```
uid = self.request.form.get("uid", self.request.get("uid"))
```

2022-02-14 22:09 UTC, ramonski commented on src/senaite/core/browser/modals/analysis.py
> +            return uid
Ah ok, I see. It is first passed as request parameter and afterwards submitted by a hidden field...

2022-02-15 09:26 UTC, xispa commented on src/senaite/core/browser/modals/analysis.py
> +            return uid
Yes, is submitted afterwards by a hidden field. Btw, I modified the code with your syntax, more cleaner

2022-02-15 09:26 UTC, xispa commented on src/senaite/core/browser/modals/templates/set_analysis_conditions.pt
> +            <table class="table table-condensed small">
Noted with thanks!

2022-02-15 09:28 UTC, xispa commented
> Only minor changes needed before we can merge it. It is a pity that the modal overlay is bound to workflow actions only: https://github.com/senaite/senaite.app.listing/blob/2.x/webpack/app/listing.coffee#L773

Yes, I noticed that too, but making it more generic was out-of-the-scope this time. Maybe next time!

2022-02-15 09:53 UTC, merged