Allow to create worksheet from samples
senaite/senaite.core pull request #1962
Opened 2022-04-09 19:09 UTC by ramonski

## Description of the issue/feature this PR addresses

Please merge https://github.com/senaite/senaite.app.listing/pull/71 first

This PR adds a new custom transition for sample listings to create a new worksheet from the selected samples.

<img width="1330" alt="Samples — SENAITE LIMS 2022-04-09 9 PM-04-59" src="https://user-images.githubusercontent.com/713193/162588243-43a80d71-1bfd-40f2-a18b-af0c37a2cb0b.png">

**NOTE**

This PR adds a new dependency to `bootstrap-select`:
https://developer.snapappointments.com/bootstrap-select

## Current behavior before PR

Only possible to add worksheets from the worksheet folder

## Desired behavior after PR is merged

Allow to create a new worksheet from selected samples

--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

2022-04-11 17:23 UTC, xispa requested changes
Excellent work, just a comment. 

As a side note for future, would be cool to make this custom transition to somehow rely on the current status of the selected items (Samples), so it wouldn't be displayed unless the selected sample had at least one analyses not yet assigned.... not for now, though.

2022-04-11 17:23 UTC, xispa commented on src/senaite/core/browser/samples/view.py
> +
Better to only display this transition on "Active" and "Received" review statuses/filters. It does not make sense for e.g. verified or published samples

2022-04-11 18:24 UTC, ramonski commented
> As a side note for future, would be cool to make this custom transition to somehow rely on the current status of the selected items (Samples), so it wouldn't be displayed unless the selected sample had at least one analyses not yet assigned....

This code snippet could be used to achieve this (code taken from `senaite.app.listing.ajax`):

```python
payload = self.get_json()
uids = payload.get("selected_uids", [])
for uid in uids:
    sample = api.get_object_by_uid(uid, default=None)
    if sample is None:
        logger.error("No sample found for UID %s" % uid)
        return False
    state = api.get_workflow_status_of(sample)
    if state not in ["Received"]:
        return False
```

But I like the idea to use the review state filter in this case.

2022-04-12 08:38 UTC, xispa approved these changes

2022-04-12 08:38 UTC, merged