Support for sharing objects across groups of clients
senaite/senaite.core pull request #2046
Opened 2022-07-06 15:43 UTC by xispa

## Description of the issue/feature this PR addresses

With https://github.com/senaite/senaite.core/pull/2004 becomes possible to share an object with multiple clients. However, user had to manually and individually pick the clients to share the content with.

This Pull Request:
- introduces the new content type `ClientsGroup` that makes the creation of client groups possible
- allows the user to choose client groups for objects that implement `IClientShareableBehavior` behavior. An object shared with a client group becomes accessible to contacts from all clients that are assigned to the selected group

## Current behavior before PR

Is not possible to share a given object with contacts from multiple clients in a single shot

## Desired behavior after PR is merged

Is possible to share a given object with contacts from multiple clients in a single shot

--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

2022-07-16 14:36 UTC, ramonski requested changes
I believe that using objects for the purpose of grouping is the wrong approach and it clutters the core without additional value (if no patients add-on is installed).
In my opinion I would rather take the approach with an additional `group` field (or annotation) in clients and use a keyword index.
Adding clients to groups would then happen in the listing via a modal/view action to add/remove to groups.
This would have the additional value to be easy filterable in the listing, e.g. by clicking on a group and showing only the clients that belong to the same group (similar to the labels in GitHub issues).

2022-07-16 14:36 UTC, ramonski commented on src/senaite/core/profiles/default/types/ClientsGroups.xml
> +        i18n:domain="senaite.diagnosis"
typo

2022-07-16 14:36 UTC, ramonski commented on src/senaite/core/behaviors/clientshareable.py
> +    """
I kind of understand what you are trying to do, but my brain turned off after 10 minutes looking at the logic of this field... Too many redirections

2022-07-18 07:44 UTC, xispa commented
> I believe that using objects for the purpose of grouping is the wrong approach and it clutters the core without additional value (if no patients add-on is installed). In my opinion I would rather take the approach with an additional `group` field (or annotation) in clients and use a keyword index. Adding clients to groups would then happen in the listing via a modal/view action to add/remove to groups. This would have the additional value to be easy filterable in the listing, e.g. by clicking on a group and showing only the clients that belong to the same group (similar to the labels in GitHub issues).

The approach you suggest by means of a new field with a "label"-like behavior looks promising. Will give a try, thanks.

2022-07-18 07:44 UTC, closed without merging