Allow to edit the analysis service sort keys in the services listing
senaite/senaite.core pull request #2131
Opened 2022-09-13 14:20 UTC by ramonski

## Description of the issue/feature this PR addresses

This PR allows to edit the analysis service sort keys in the services listing:

<img width="1140" alt="Analysis Services — SENAITE LIMS 2022-09-13 4 PM-17-48" src="https://user-images.githubusercontent.com/713193/189925946-4216e6e9-84df-4c79-955a-14ff9a5c2921.png">

## Current behavior before PR

Service sort keys could only be edited in the edit view

## Desired behavior after PR is merged

Service sort keys can be edited inside the services listing

--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

2022-09-13 20:16 UTC, ramonski commented on src/bika/lims/browser/analyses/view.py
> +                item["help"]["Result"] = _(
Compatibility for https://github.com/senaite/senaite.app.listing/pull/85

2022-09-14 04:25 UTC, xispa requested changes
The Unit is displayed next to the SortKey input field, which is confusing.

On another note, how is the Data Manager for AnalysisService related with this "SortKey" functionality?. I am not sure if I am missing something.

2022-09-14 04:53 UTC, ramonski commented
> The Unit is displayed next to the SortKey input field, which is confusing.
> 
> On another note, how is the Data Manager for AnalysisService related with this "SortKey" functionality?. I am not sure if I am missing something.

Ups, apologies. Going to change that.

The datamanagers are called from here:
https://github.com/senaite/senaite.app.listing/blob/2.x/src/senaite/app/listing/ajax.py#L392

Probably better to rename them one day into `IAjaxFieldManager`

2022-09-14 05:06 UTC, ramonski commented
Oh, the behavior with the unit comes actually from here:
https://github.com/senaite/senaite.app.listing/blob/2.x/webpack/app/components/TableCell.coffee#L420

Probably because numeric fields used to be either result or interim fields...

2022-09-19 09:44 UTC, ramonski commented
Implicit Unit injection was removed in https://github.com/senaite/senaite.app.listing/pull/86 and explicitly added in https://github.com/senaite/senaite.core/pull/2134

2022-09-19 14:04 UTC, xispa approved these changes

2022-09-19 15:01 UTC, merged