getName for Supplier from pc and not bsc catalog
senaite/senaite.core pull request #2183
Opened 2022-11-15 14:18 UTC by Lunga001

## Description of the issue/feature this PR addresses

Linked issue: https://github.com/senaite/senaite.core/issues/2182

## Current behavior before PR
Instrument Supplier field does not  get set on import

## Desired behavior after PR is merged
Instrument Supplier field shoud be  set on import

--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

2022-11-15 16:47 UTC, xispa requested changes
Thanks @Lunga001 . Would you mind to replace the changelog entry by something like "Fix instrument supplier does not load on test data import"?

2022-11-15 16:50 UTC, ramonski commented
I think this is not the correct fix. Suppliers should be in the setup catalog, thus adding an additional column to this catalog would be the right fix in my opinion.

2022-11-15 18:42 UTC, Lunga001 commented
Works also if the title is used on senaite_catalog_setup to find the supplier. Please do let me know show more changes be required.

2022-11-17 13:24 UTC, xispa approved these changes

2022-11-17 13:24 UTC, merged