Apply category sort order on analysis specifications
senaite/senaite.core pull request #2191
Opened 2022-11-23 12:32 UTC by anneline

## Description of the issue/feature this PR addresses

Linked issue: https://github.com/senaite/senaite.core/issues/

## Current behavior before PR
In analysis specification edit, analysis service categories were sorted alphabetically
![97869461-c1c7-412f-8234-c47227b6b0a3](https://user-images.githubusercontent.com/1196003/203547654-6aa981f7-0f3e-4ec2-bdac-b43390e260a5.png)

## Desired behavior after PR is merged
In analysis specification edit, analysis service categories sorted by sort key
-
![a95094b8-ab27-41e7-9540-91b62eb112b1](https://user-images.githubusercontent.com/1196003/203547750-f28cba6f-9591-4cfa-afb6-c6ac9f849130.png)
-
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

2022-11-24 10:02 UTC, ramonski requested changes

2022-11-24 10:02 UTC, ramonski commented on src/bika/lims/browser/widgets/analysisspecificationwidget.py
> +        bsc = getToolByName(self.context, "senaite_catalog_setup")
Please use simply `catalog` as variable, because this catalog is no longer named `bika_setup_catalog`. You might also consider to use `api.get_tool` instead of `getToolByName`

2022-11-24 10:02 UTC, ramonski commented on src/bika/lims/browser/widgets/analysisspecificationwidget.py
> +                                    sorted(self.categories, key=lambda x: x[1]))
Ok, above you have already *all* categories in the right order. It would make more sense to simply filter out those that are not found instead of sorting the found ones afterwards.
Use therefore the built in `filter` function of Python, e.g. like this:

```python
from bika.lims import api
from senaite.core.catalog import SETUP_CATALOG

catalog = api.get_tool(SETUP_CATALOG)
all_categories = catalog({"portal_type": "AnalysisCategory", "sort_on: "sortable_title"})
sorted_categories = filter(lambda cat: api.get_title(cat) in self.found_categories, all_categories)
self.categories = map(api.get_object, sorted_categories)
```

Note: This code is not tested;)

2022-11-24 10:02 UTC, ramonski commented on src/bika/lims/browser/widgets/analysisspecificationwidget.py
> +                self.categories.append((category,cat_order))
Please simply collect here the category title in a instance variable, e.g.:

```
if category not in self.found_categories:
    self.found_categories.append(category)
```

This one is used later to filter out the already sorted categories.

2023-01-10 10:45 UTC, ramonski commented
Hi @anneline, what is the status of this PR?

2023-01-26 09:45 UTC, anneline commented
Updated as requested. Thanks Ramon.

2023-01-27 08:24 UTC, ramonski commented
Hi @anneline, did you commit the changes? I do not see any difference to the last time...

2023-01-27 08:25 UTC, ramonski commented
Please also ensure that the tests are passing, thanks!

2023-03-15 11:03 UTC, anneline commented
Done. Lint error removed.

2023-03-15 15:01 UTC, ramonski commented
Hi @anneline,

the requested changes are not here: https://github.com/senaite/senaite.core/pull/2191/files

Please change the code as requested in the comments above and commit/push the changes to this repository again.

2026-05-29 19:50 UTC, ramonski commented
Ported into https://github.com/senaite/senaite.core/pull/2927

2026-05-29 19:50 UTC, closed without merging