Fix #2428 an error raise when request is None if create analysisspec with resultsrange by JSONAPI
senaite/senaite.core pull request #2431
Opened 2023-11-19 15:53 UTC by fengyundeng

## Description of the issue/feature this PR addresses

Linked issue: https://github.com/senaite/senaite.core/issues/

## Current behavior before PR
in src/bika/lims/validators.py, line 818
          request = kwargs.get("REQUEST", {})
request is None, when create analysisspec by JSONAPI.
then, in src/bika/lims/validators.py, line 829
          service_uids = request.get("uids", [])
raise an error, 'NoneType' object has no attribute 'get'

## Desired behavior after PR is merged
fix the bug when "request" is None.
the analysisspec with "ResultsRange" by JSONAPI created work fine.

--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

2023-11-19 16:03 UTC, fengyundeng commented
I am new with Senaite.LIMS. When i want to create analysis spec by JSONAPI, i found the bug "request" is None and raise an error 'NoneType' object has no attribute 'get'. the fix is work fine for me. But i didn't go very deeper in code (as I'm new one). So please check the fix is in the way properly.

2023-11-22 15:47 UTC, xispa requested changes
Thanks @fengyundeng , please add an entry to the changelog as well: https://github.com/senaite/senaite.core/blob/2.x/CHANGES.rst

2023-11-22 15:47 UTC, xispa commented on src/bika/lims/validators.py
> +            request = {}
You can simplify with:

```python
request = kwargs.get("REQUEST") or {}
```

2023-11-23 12:54 UTC, fengyundeng commented on src/bika/lims/validators.py
> +            request = {}
thanks @xispa for the nice feedback.

2023-11-25 06:20 UTC, fengyundeng commented
sorry for caused the confusion.
i'm not familiar with pull process.

2023-11-26 15:32 UTC, xispa approved these changes

2023-11-26 15:40 UTC, merged