keep the same class-method name in both
senaite/senaite.core pull request #2445
Opened 2023-12-08 09:23 UTC by fengyundeng

## Description of the issue/feature this PR addresses

Linked issue: https://github.com/senaite/senaite.core/issues/

## Current behavior before PR

class InstrumentCSVResultsFileParser(InstrumentResultsFileParser)
        def splitLine(self, line)

class InstrumentTXTResultsFileParser(InstrumentResultsFileParser)
        def split_line(self, line)

## Desired behavior after PR is merged

keep the same class-method name in "class InstrumentTXTResultsFileParser(InstrumentResultsFileParser)", as in "class InstrumentCSVResultsFileParser(InstrumentResultsFileParser)"
--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

2023-12-11 20:23 UTC, ramonski requested changes
Thanks for the consistency change @fengyundeng!

Would you mind to add a changelog entry on top of the file https://github.com/senaite/senaite.core/blob/2.x/CHANGES.rst with the updated title?

2023-12-12 01:42 UTC, fengyundeng commented
Hi @ramonski , the CHANGES.rst is updated.
BTW, is it better to "Pull requests and add CHANGES.rst at the same time" when i could contribute some in project in future?

2023-12-12 09:05 UTC, ramonski commented
Hi @fengyundeng,

The update to the changelog are not yet pushed to this PR, see
https://github.com/senaite/senaite.core/pull/2445/files

Regarding your question:
You need to first create a PR to get a number. In your case #2445.
This PR number is then referred in the changelog, e.g.:

```
Changelog
=========

2.5.0 (unreleased)
------------------

- #2445 Rename split_line -> splitLine in InstrumentTXTResultsFileParser for consistency
- ...
```

Please always put your changelog above the others, so that we have a proper order.

Thanks!

2023-12-19 06:55 UTC, ramonski commented
Hi @fengyundeng,
would you mind to add the changelog line you did in #2447 into this PR please?
Thanks

2023-12-19 11:48 UTC, fengyundeng commented
Hi @ramonski , i tried to, but i didn't find where to add CHANGES.rst to "Files changed" in this PR.
Each time when i edited CHANGES.rst, i always need to create a new PR?
sorry. i'm a new guy in github.

2023-12-19 17:30 UTC, ramonski commented
Hi @fengyundeng,
no worries, then we merge both of your PRs to keep it simple.
Thanks for your your contribution!

2023-12-19 17:31 UTC, ramonski approved these changes

2023-12-19 17:31 UTC, merged