Fix default landing page is not considered in clients listing
senaite/senaite.core pull request #2459
Opened 2023-12-28 17:50 UTC by xispa

## Description of the issue/feature this PR addresses

This Pull Request fixes the default landing page when a client from the folder listing is selected as well as when a client login the system and no default wide landing page is set in classic setup.

This functionality was once provided by means of the registry record with key `bika.lims.client.default_landing_page`, that is no longer available in 2.x instances, but in those upgraded from 1.x

## Current behavior before PR

The legacy setting for the default landing page is no longer used

## Desired behavior after PR is merged

The legacy setting for the default landing page is ported to SENAITE registry

--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

2023-12-28 18:25 UTC, xispa commented
This whole dance is not worth. Closing

2023-12-29 09:42 UTC, xispa commented
Re-opening this one because of legacy compatibility. We'll need to revisit this landing page thing at some point though.

2023-12-29 15:59 UTC, ramonski requested changes
Thanks Jordi!
Just one thing:
Can you move the key "client_landing_page" into the config as a variable?

2023-12-29 16:47 UTC, ramonski commented
Please also add our `@upgradestep(product, version)` decorator around the `import_registry` function. I've seen that add-ons might loose the navigation settings.

2023-12-29 17:21 UTC, xispa commented
> Thanks Jordi! Just one thing: Can you move the key "client_landing_page" into the config as a variable?

Done

2023-12-29 17:22 UTC, xispa commented
> Please also add our `@upgradestep(product, version)` decorator around the `import_registry` function. I've seen that add-ons might loose the navigation settings.

Done with https://github.com/senaite/senaite.core/pull/2459/commits/e4926a5bfb0a87474ea03af64bd48324e2b20ed2

2023-12-29 20:10 UTC, ramonski approved these changes

2023-12-29 20:10 UTC, merged