Changed spelling error.
senaite/senaite.core pull request #2473
Opened 2024-02-02 12:38 UTC by dietervdwes

## Description of the issue/feature this PR addresses
None - picked up a spelling error.

## Current behavior before PR
Spelling mistake "tha"

## Desired behavior after PR is merged
Spelling mistake fixed "that"
--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

2024-02-06 12:49 UTC, xispa requested changes
Thanks @dietervdwes for your contribution. However, note that from to time we run an script relying on `i18ndude` that searches for localized strings across all `.py` and `.pt` files and rebuilds the `.po` files in accordance. This very same script uploads the updated locales to [transifex](https://app.transifex.com/senaite/senaite-core/dashboard/). 

Therefore, for this fix error to be kept in further releases, you have to modify the source at https://github.com/senaite/senaite.core/blob/44675d7db55aef7be8693223528ca9db794f25f0/src/bika/lims/content/bikasetup.py#L539

2024-02-16 10:17 UTC, dietervdwes commented
Thanks @xispa  for the explanation - it helps. Hopefully the review is fine now.

2024-02-18 12:51 UTC, xispa approved these changes
Thanks @dietervdwes

2024-02-18 15:54 UTC, xispa approved these changes

2024-02-18 15:55 UTC, merged