Migrate InstrumentTypes to DX
senaite/senaite.core pull request #2551
Opened 2024-05-16 08:44 UTC by Bugerman58

## Description of the issue/feature this PR addresses

This PR migrates the AT InstrumentType(s) to Dexterity types for Python 3 compatibility.

## Current behavior before PR

InstrumentType(s) are content types based on the Archetypes framework

## Desired behavior after PR is merged

InstrumentType(s) are content types based on the Dexterity framework

--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

2024-05-22 09:52 UTC, Bugerman58 commented
Hi @xispa and @ramonski 
this PR ready for review.

2024-05-27 07:04 UTC, xispa requested changes
Thanks @Bugerman58 !, some minor changes required!

2024-05-27 07:04 UTC, xispa commented on src/senaite/core/browser/controlpanel/instrumenttypes/view.py
> +        )
Use the default icon provided by the type:

```python
self.icon = api.get_icon("InstrumentTypes", html_tag=False)
```

2024-05-27 07:04 UTC, xispa commented on src/senaite/core/browser/controlpanel/instrumenttypes/view.py
> +from bika.lims import bikaMessageFactory as _
Better use `senaiteMessageFactory`:

```python
from bika.lims import senaiteMessageFactory as _
```

2024-05-27 07:04 UTC, xispa commented on src/senaite/core/browser/controlpanel/instrumenttypes/view.py
> +        self.show_select_row = False
Remove `self.show_select_row`, this attribute was removed from the base class

2024-05-27 07:04 UTC, xispa commented on src/senaite/core/browser/controlpanel/instrumenttypes/view.py
> +        self.pagesize = 25
Remove `self.pagesize` to stick to [default's (50)](https://github.com/senaite/senaite.app.listing/blob/2.x/src/senaite/app/listing/view.py#L173)

2024-05-27 07:04 UTC, xispa commented on src/senaite/core/browser/controlpanel/instrumenttypes/view.py
> +        self.description = ""
Remove `self.description = ""`, it is already set to empty in the base class

2024-05-27 07:04 UTC, xispa commented on src/senaite/core/upgrade/v02_06_000.zcml
> +      destination="2630"
Update `profiles/metadata.xml` in accordance

2024-05-27 08:31 UTC, xispa approved these changes

2024-05-27 08:31 UTC, merged