Migrate SamplingDeviations to DX
senaite/senaite.core pull request #2552
Opened 2024-05-16 11:30 UTC by Bugerman58

## Description of the issue/feature this PR addresses

This PR migrates the AT SamplingDeviation and SamplingDeviations to Dexterity types for Python 3 compatibility.

## Current behavior before PR

SamplingDeviation and SamplingDeviations are content types based on the Archetypes framework

## Desired behavior after PR is merged

SamplingDeviation and SamplingDeviations are content types based on the Dexterity framework

--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

2024-05-27 10:19 UTC, Bugerman58 commented
Hi @xispa this PR ready for review.

2024-05-31 10:24 UTC, xispa requested changes
Excellent!, just three small things left!

2024-05-31 10:24 UTC, xispa commented on src/senaite/core/browser/controlpanel/samplingdeviations/view.py
> +                "transitions": [{"id": "deactivate"}, ],
Remove this `transitions` attribute. Listing displays the available transitions for the selected object automatically based on the workflow(s) the object is bound to.

2024-05-31 10:24 UTC, xispa commented on src/senaite/core/browser/controlpanel/samplingdeviations/view.py
> +                "transitions": [{"id": "activate"}, ],
Remove `transitions` here too

2024-05-31 10:24 UTC, xispa commented on src/senaite/core/browser/controlpanel/samplingdeviations/view.py
> +                "transitions": [{"id": "empty"}, ],
Remove this `transitions` attribute cause default transitions "Activate" (if deactivated) or "Deactivate" (if active) are not displayed when "All" filter is selected

2024-05-31 10:39 UTC, xispa approved these changes

2024-05-31 10:39 UTC, merged