Fix SubGroups migration typo
senaite/senaite.core pull request #2557
Opened 2024-05-20 08:46 UTC by toropok

Fix default factory typo from #2545 

## Description of the issue/feature this PR addresses

typo 

## Current behavior before PR

## Desired behavior after PR is merged

fix 

--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

2024-05-20 08:56 UTC, ramonski requested changes
Thanks for the quick fixture!
However, you need to re-import the `typestool` so that these changes take effect.
Therefore, you new a new upgrade step and metadata version

2024-05-20 09:06 UTC, toropok commented
> Thanks for the quick fixture! However, you need to re-import the `typestool` so that these changes take effect. Therefore, you new a new upgrade step and metadata version

@ramonski 

sorry, I've got it wrong. Is that right now?

2024-05-20 20:31 UTC, ramonski approved these changes
Great, thanks!

2024-05-20 20:31 UTC, merged

2024-05-20 20:49 UTC, ramonski commented
Ah, now I get what went wrong.
The migrated objects were created already as `ContainerType` types:

<img width="923" src="https://github.com/senaite/senaite.core/assets/713193/8db6b2d7-0720-429a-9794-c0f2d5e75156">

<img width="1683" src="https://github.com/senaite/senaite.core/assets/713193/81b2f7e9-68a0-45ba-95c8-ec79a203dd68">

Ok, that's indeed kind of bad, but I guess it should be ok since we fixed it so quick.

2024-05-21 08:13 UTC, toropok commented
> Ok, that's indeed kind of bad, but I guess it should be ok since we fixed it so quick.

that's absolutely my fault, I will do my best to not let it happen again.. thanks for your assistance and support