Migrate AnalysisCategories to DX
senaite/senaite.core pull request #2567
Opened 2024-05-31 13:49 UTC by Bugerman58

## Description of the issue/feature this PR addresses

This PR migrates the AT AnalysisCategory and AnalysisCategories to Dexterity types for Python 3 compatibility.

## Current behavior before PR

AnalysisCategory and AnalysisCategories are content types based on the Archetypes framework

## Desired behavior after PR is merged

AnalysisCategory and AnalysisCategories are content types based on the Dexterity framework

--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

2024-06-03 11:08 UTC, Bugerman58 commented
@xispa Hi, this PR ready for review. pls, check it

2024-06-11 09:06 UTC, xispa requested changes
Thanks @Bugerman58 !

There is a [subscriber that reindexes all sample analyses when the title of the category changes](https://github.com/senaite/senaite.core/blob/2.x/src/bika/lims/subscribers/objectmodified.py#L50). This subscriber won't be called because the event is only triggered for AT content types. I do know that the dance is weird, takes ages to complete and is something we need to fix. But keep it for now, please. I will open a PR after yours to remove the `getCategoryTitle` metadata and fix that thing. Meanwhile, please create a new subscriber specific for analysiscategory at `senaite.core.subscribers`.

2024-06-11 09:06 UTC, xispa commented on src/bika/lims/workflow/analysiscategory/guards.py
> +from bika.lims.catalog.bikasetup_catalog import SETUP_CATALOG
better import the catalog id from `senaite.core` instead:

```python
from senaite.core.catalog import SETUP_CATALOG
```

2024-06-11 09:06 UTC, xispa commented on src/bika/lims/workflow/analysiscategory/guards.py
> +def guard_deactivate(analysis_category):
I see you replaced that old-school `workflow_script_deactivate` by this guard handler, good job!

2024-06-11 09:06 UTC, xispa commented on src/senaite/core/content/analysiscategory.py
> +            default="Select the responsible department",
Please do `unicode` for `i18n` resources. See this discussion: https://github.com/senaite/senaite.core/pull/2566#pullrequestreview-2089339759

2024-06-11 09:06 UTC, xispa commented on src/senaite/core/content/analysiscategory.py
> +        limit=5,
Remove `limit=5`, it is the default. See https://github.com/senaite/senaite.core/blob/2.x/src/senaite/core/z3cform/widgets/queryselect/widget.py#L118

2024-06-13 21:01 UTC, xispa approved these changes
Excellent, thanks!

2024-06-13 21:01 UTC, merged