Support multiple files for datagrid fields
senaite/senaite.core pull request #2586
Opened 2024-07-13 21:18 UTC by ramonski

## Description of the issue/feature this PR addresses

This PR allows file fields in Data Grid Rows, so that multiple files can be uploaded in a single field:

<img width="896" src="https://github.com/user-attachments/assets/fcd8b6c0-616f-4cf7-8d01-6e5de17642a8">
 
## Current behavior before PR

There is no usable way to allow multiple files in a single field in SENAITE

## Desired behavior after PR is merged

Multiple fields can be uploaded in Data Grid Field Rows

--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

2024-07-15 14:20 UTC, xispa requested changes
Fantastic, it works like a charm!

I've left three minor comments. Besides, in view mode, the widget is rendered like this, with filenames in plain text:

![Captura de 2024-07-15 16-13-22](https://github.com/user-attachments/assets/fe2ea1b5-b6b2-4156-a0cc-c569cf07e371)

I think would be better if we render links for direct download. What do you think?

2024-07-15 14:20 UTC, xispa commented on src/senaite/core/z3cform/widgets/datagrid/datagridrow_file_input.pt
> +                  i18n:translate="">100</span>
Remove `i18n:translate`

2024-07-15 14:20 UTC, xispa commented on src/senaite/core/z3cform/widgets/datagrid/datagridrow_file_input.pt
> +                  i18n:translate="">ContentType</span>,</tal:doc_type>
Remove `i18n:translate`

2024-07-15 14:20 UTC, xispa commented on src/senaite/core/z3cform/widgets/datagrid/README.md
> +from senaite.core.z3cform.widgets.datagrid import DataGridWidget
Missing imports: 

```python:
from zope import schema
from zope.interface import Interface
```

2024-07-16 09:35 UTC, ramonski commented
Hey Jordi, thanks for your review! I addressed all the points you mentioned and it is ready for review again:)

2024-07-16 10:18 UTC, xispa approved these changes

2024-07-16 10:18 UTC, merged