Subgroups sort by sort_key
senaite/senaite.core pull request #2652
Opened 2024-12-02 13:22 UTC by Lunga001

## Description of the issue/feature this PR addresses

Linked issue: https://github.com/senaite/senaite.core/issues/2651

## Current behavior before PR
Subgroups are not sorted by sort key 

## Desired behavior after PR is merged
Sub groups to

--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

2025-01-31 10:34 UTC, ramonski requested changes
Thanks Lunga for this fixture!
Just two small changes are required before we can merge it.

2025-01-31 10:34 UTC, ramonski commented on src/senaite/core/content/subgroup.py
> +        except Exception:
please avoid to use blind exceptions. Catch `TypeError` and `ValueError` here.

2025-01-31 10:34 UTC, ramonski commented on src/senaite/core/upgrade/v02_06_000.py
> +            obj.sort_key = api.to_float(obj.sort_key)
Add a fallback to `api.to_float(obj.getSortKey(), 0.0)`

2025-02-03 14:31 UTC, Lunga001 commented
Thank @ramonski, added the changes.

2025-02-04 09:35 UTC, ramonski approved these changes
Thanks Lunga!

2025-02-04 09:35 UTC, merged